apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: {{ .Values.app.name }}
    build: "${CICD_EXECUTION_SEQUENCE}"
  name: {{ .Values.app.name }}
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - backend:
          serviceName: {{ .Values.app.name }}
          servicePort: 80
