stages:
- name: Build
  steps:
  - runScriptConfig:
      image: dyadin/toolbox
      shellScript: |-
        echo "Starting build phase"
        sed -i "s/V2/1.0.${CICD_EXECUTION_SEQUENCE}/" index.html
        echo "Finished build phase"
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: dyadin/rancher-demo:${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: index.docker.io
- name: Catalog
  steps:
  - publishCatalogConfig:
      path: ./charts-src
      catalogTemplate: Rancher-Demo
      version: ${CICD_EXECUTION_SEQUENCE}
      gitUrl: https://github.com/zm1990s/kubernetes-charts.git
      gitBranch: master
      gitAuthor: dyadin
      gitEmail: zm1990s@gmail.com
    envFrom:
    - sourceName: github-secret
      sourceKey: USERNAME
      targetKey: USERNAME
    - sourceName: github-secret
      sourceKey: PASSWORD
      targetKey: PASSWORD
timeout: 60
notification: {}
