apiVersion: v1
kind: Service
metadata:
  name: pipeline-demo-svc
  namespace: pipeline
  labels:
    app: pipeline-demo
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 30080
  selector:
    app: pipeline-demo
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pipeline-demo
    from: pipeline
  name: pipeline-demo
  namespace: pipelinedemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pipeline-demo
  template:
    metadata:
      labels:
        app: pipeline-demo
    spec:
      containers:
      - image: dyadin/rancher-demo:${CICD_EXECUTION_SEQUENCE}
        imagePullPolicy: Always
        name: demo
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
