app:
  name: nginx

deployment:
  replicas: "1"
  pullpolicy: IfNotPresent
  image: dyadin/rancher-demo:${CICD_EXECUTION_SEQUENCE}

service:
  type: ClusterIP

ingress:
  host: pipeline.youjiqing.club
